PR for STACK-264
a10networks/a10-saltstack pull request #30
Opened 2019-06-26 07:57 UTC by hthompson6

2019-07-11 20:48 UTC, ghost requested changes
Can we look at using `responses` for the HTTP lib testing? 

If not possible, please respond to this comment with the reasoning.

2019-07-11 20:48 UTC, mdurrant-b3 commented on tests/unit/client/test_axapi_http.py
> +    def _patch_wrap(self, path):
Excessive patching is a code smell.  Use responses to test requests.

2019-07-15 03:01 UTC, hthompson6 commented
> Can we look at using `responses` for the HTTP lib testing?
> 
> If not possible, please respond to this comment with the reasoning.

Make no mistake. The responses library is itself just a patch of the requests library that's been wrapped with extra functionality. It's biggest contribution is the inclusion of callbacks and ensuring the that desired URL is hit by default.

I see why this library could be useful, but we don't have enough tests in which we care about the response, the url, and the method type to warrant using it. It just wouldn't get us anything extra in terms of testing or readability at least so far as how we'd end up using it.

Instead, I've gone about removing some dependencies and imports that weren't be using. I have noticed that the Session class has been utilized differently in the acos client version of the AXAPI to allow for max retries and timeouts. I'll add a story to investigate and mirror those changes.

2019-07-24 17:17 UTC, mdurrant-b3 commented
👍

2019-07-24 17:17 UTC, ghost approved these changes

2019-07-24 17:18 UTC, merged